### PR TITLE
Add empty __init__.py

### PR DESCRIPTION
**Pull request by mbolivar**
Make this repository a Python package. Needed so it's importable from zmp-build

### CODE REVIEW

**Comment by mbolivar** [comment]
@mike-scott I'm just going to merge this one; it's super trivial

**Comment by doanac** [comment]
@mbolivar - this is a new repo. Let me know if there's some CI integration needed here.

**Comment by mbolivar** [comment]
> @mbolivar - this is a new repo. Let me know if there's some CI integration needed here.

Andy if you can run `py.test test_*.py` that'd be a great start, thanks!

(Note the presence of a requirements.txt)

**Comment by doanac** [comment]
I've got a weird issue with requirements.txt. I can't install editdistance==0.5.2. pip3 will only install the 0.4 version. Its weird, because 0.5.2 is on pypi.

**Comment by mbolivar** [comment]
That's OK, the pygit2 version is the latest that works on Ubuntu, I'm sure yours is fine too. Thanks for this!

**Pull request merged**
